import HASH from "./HASH.mjs";
export const SITE_AUTHOR = "John Henry";
export const SITE_TITLE = "John Henry";
export const SITE_FAVICON_PATH = "image/iajh.png";
export const SITE_FAVICON_TYPE = "image/png";
export const SITE_SERVICE_WORKER = "";
export const SITE_BASE_PATH = "/";
export const SITE_CDN_URL = "/";
export const SITE_BLOG_PAGE_SIZE = 4;
export const SITE_LIB_URL = "http://localhost:3001/";
export const SITE_CANONICAL_URL = "https://johnhenry.github.io/";
export const SITE_DESCRIPTION = "John Henry's Person Portfolio and Blog";
export const SITE_KEYWORDS = [];
export const TAG_MANAGER_ID = "";
export const BUILD_DATE = new Date().toISOString();
export const BUILD_HASH = HASH;
export const BUILD_META = "";
