name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install 🪛
        run: npm install

      - name: Build 🏭
        env:
          PUBLIC_SITE_AUTHOR: ${{ secrets.PUBLIC_SITE_AUTHOR }}
          PUBLIC_SITE_TITLE: ${{ secrets.PUBLIC_SITE_TITLE }}
          PUBLIC_SITE_CANONICAL_URL: ${{ secrets.PUBLIC_SITE_CANONICAL_URL }}
          PUBLIC_SITE_DESCRIPTION: ${{ secrets.PUBLIC_SITE_DESCRIPTION }}
          PUBLIC_SITE_KEYWORDS: ${{ secrets.PUBLIC_SITE_KEYWORDS }}
          PUBLIC_SITE_LIB_URL: ${{ secrets.PUBLIC_SITE_LIB_URL }}
          PUBLIC_BUILD_META: ${{ secrets.PUBLIC_BUILD_META }}
          PUBLIC_BUILD_HASH: ${{ secrets.PUBLIC_BUILD_HASH }}
          PUBLIC_TAG_MANAGER_ID: ${{ secrets.PUBLIC_TAG_MANAGER_ID }}
          PUBLIC_SITE_SERVICE_WORKER: ${{ secrets.PUBLIC_SITE_SERVICE_WORKER }}
          PUBLIC_SITE_BASE_PATH: ${{secrets.PUBLIC_SITE_BASE_PATH}}
          PUBLIC_SITE_CDN_URL: ${{ secrets.PUBLIC_SITE_CDN_URL }}
        run: npm run build

      - name: Deploy Public 🚀
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "public" # optional: defaults to entire repository

      - name: Deploy Static 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: static # The branch the action should deploy to.
          folder: dist/static # The folder the action should deploy.
