name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install 🪛
        run: npm install

      - name: Build 🏭
        env:
          SITE_AUTHOR: ${{ secrets.PUBLIC_SITE_AUTHOR }}
          SITE_TITLE: ${{ secrets.PUBLIC_SITE_TITLE }}
          SITE_CANONICAL_URL: ${{ secrets.PUBLIC_SITE_CANONICAL_URL }}
          SITE_DESCRIPTION: ${{ secrets.PUBLIC_SITE_DESCRIPTION }}
          SITE_KEYWORDS: ${{ secrets.PUBLIC_SITE_KEYWORDS }}
          SITE_LIB_URL: ${{ secrets.PUBLIC_SITE_LIB_URL }}
          BUILD_META: ${{ secrets.PUBLIC_BUILD_META }}
          BUILD_HASH: ${{ secrets.PUBLIC_BUILD_HASH }}
          TAG_MANAGER_ID: ${{ secrets.PUBLIC_TAG_MANAGER_ID }}
          SITE_SERVICE_WORKER: ${{ secrets.PUBLIC_SITE_SERVICE_WORKER }}
          SITE_BASE_PATH: ${{secrets.PUBLIC_SITE_BASE_PATH}}
        run: npm run build && npm run build:deno

      - name: Deploy Static 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: dist # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.

      - name: Deploy SSR 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: ssr # The branch the action should deploy to.
          folder: ssr # The folder the action should deploy.
