name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Doppler 🏣
        uses: dopplerhq/cli-action@v3

      - name: Setup node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install 🪛
        run: npm ci

      - name: Build 🏭
        env:
          PUBLIC_SITE_AUTHOR: ${{ secrets.PUBLIC_SITE_AUTHOR }}
          PUBLIC_SITE_TITLE: ${{ secrets.PUBLIC_SITE_TITLE }}
          PUBLIC_SITE_CANONICAL_URL: ${{ secrets.PUBLIC_SITE_CANONICAL_URL }}
          PUBLIC_SITE_DESCRIPTION: ${{ secrets.PUBLIC_SITE_DESCRIPTION }}
          PUBLIC_SITE_KEYWORDS: ${{ secrets.PUBLIC_SITE_KEYWORDS }}
          PUBLIC_SITE_LIB_URL: ${{ secrets.PUBLIC_SITE_LIB_URL }}
          PUBLIC_BUILD_META: ${{ secrets.PUBLIC_BUILD_META }}
          PUBLIC_BUILD_HASH: ${{ secrets.PUBLIC_BUILD_HASH }}
          PUBLIC_TAG_MANAGER_ID: ${{ secrets.PUBLIC_TAG_MANAGER_ID }}
          PUBLIC_SITE_SERVICE_WORKER: ${{ secrets.PUBLIC_SITE_SERVICE_WORKER }}
          PUBLIC_SITE_BASE_PATH: ${{secrets.PUBLIC_SITE_BASE_PATH}}
          PUBLIC_SITE_CDN_URL: ${{ secrets.PUBLIC_SITE_CDN_URL }}
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_PROD_TOKEN }}
        run: npm run build:doppler

      - name: Disable Jekyll ❗🌓
        run: touch dist/static/.nojekyll

      - name: Deploy Public 🚀
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks --delete --exclude "favicon.ico" --exclude "manifest.json" --exclude "robots.txt"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "public" # optional: defaults to entire repository

      - name: Deploy Static 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: static # The branch the action should deploy to.
          folder: dist/static # The folder the action should deploy.

      - name: Finalizing summary
        run: |
          echo "# Site Map" >> $GITHUB_STEP_SUMMARY
          echo '```xml' >> $GITHUB_STEP_SUMMARY
          cat dist/static/sitemap-index.xml >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
